version: '3.8'

services:
  dotnet-app:
    build:
      context: .
      dockerfile: src/LoadTesterSample/Dockerfile
    ports:
      - "5001:5000" # Expose the app on localhost
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - test-network

  k6:
    image: grafana/k6
    depends_on:
      - dotnet-app
    networks:
      - test-network
    volumes:
      - ./scripts:/scripts
    working_dir: /scripts
    environment:
      - K6_WEB_DASHBOARD=true
    ports:
      - "5665:5665"
    command:
      [
        "run",
        "-o",
        "influxdb=http://influxdb:8086/k6",
        "/scripts/loadtest.js"
      ]

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086" # InfluxDB HTTP API
    networks:
      - test-network
    environment:
      INFLUXDB_DB: k6
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin123
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000" # Grafana dashboard
    depends_on:
      - influxdb
    networks:
      - test-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/var/lib/grafana/dashboards
      - ./provisioning:/etc/grafana/provisioning

networks:
  test-network:
    driver: bridge

volumes:
  influxdb-data:
  grafana-data:
